name: WebAssembly

on: [push,pull_request]

jobs:
  build-wasm:
    name: "build-test-wasm"
    runs-on: ubuntu-22.04

    steps:
    - name: 'Free up disk space'
      run: |
        # Workaround for https://github.com/actions/virtual-environments/issues/709
        df -h
        sudo apt-get update
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf /usr/share/dotnet/
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

    - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version: '18'

    - name: Install
      run: |
        npm install

    - name: Build
      run: |
        npm run build

    - name: Generate TypeScript, JavaScript package
      run: |
        npm run bindgen:typescript

    - name: Build TypeScript, JavaScript package
      working-directory: ./typescript
      run: |
        npm install
        npm run build

    - name: Generate Python packages
      run: |
        npm run bindgen:python

    - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
      with:
        python-version: '3.10'

    - name: Test Python WASI
      working-directory: ./python/itkwasm-isic-superpixel-wasi
      run: |
        pip install hatch
        hatch run test
